### ISSUE TITLE
Support Options?

### ISSUE THREAD

**Issue by andrewatfornax** [Pwd9000-ML/blog-devto#2]
Any chance of adding support for AzureDevOps.WikiPDFExport options, like --breakPage, --css, --highlight-code, --footer-template, and --header-template?

That would make this really excellent :-)

Thanks!

**Comment by Pwd9000-ML** [comment]
That would be awesome.
Unfortunately I'm not a maintainer of the tool but more a consumer of it. I think these would be great additions, but you should message the original project and maintainer here: https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-WikiPDFExport-Tasks
