### ISSUE TITLE
Connect-AzAccount Not Recognized 

### ISSUE THREAD

**Issue by kushalg-1212** [Pwd9000-ML/blog-devto#35]
I followed your tutorial about VM Power state 
to shutdown , start VM . 
Thanks for the guide 

I followed all required steps and i think i have some error on Connect-AzAccount , it says not recognized cmdlet 

NOTE : I did uncommitted the module function on Requirements.psd1

**Comment by Pwd9000-ML** [comment]
Hi there,
Thanks for highlighting this issue.

It seems that in the past when this post was originally created, at the time when creating a PowerShell Function App, the AZ module was installed automatically as part of the deployment.
This is now not the case and now needs to be done by uncommenting the requirements.psd1 file in the Function Apps **'App files'** as you have rightfully mentioned.

I have updated the article to point out this step!
I have also updated the PowerShell version to 7.2, and the Function runtime to 4 in the scripts!!

![image](https://user-images.githubusercontent.com/44137582/190125030-8c59ec91-0e3d-4ef5-b782-fd121b775dc6.png)

Thank you for the collaboration!

**Comment by kushalg-1212** [comment]
it should be 4 or something , i fixed it by using the version 4

**Comment by Pwd9000-ML** [comment]
Yes, that's correct, I have also updated the function app runtime to be v4.
You can see on the blog post this change:

![image](https://user-images.githubusercontent.com/44137582/190127999-c972a207-4634-4736-96d2-b4f30bca94b0.png)

Function version runtimes are now **v4** instead of **v3**

**Comment by kushalg-1212** [comment]
thanks
